/**
 * Template-based fallback quiz, used when the offline pack can't be
 * generated by Gemini (no API key, free-tier quota exhausted, network
 * down, etc.). Builds up to 10 simple questions by reading structured
 * fields off the itinerary — no AI required, no network required, no
 * destination-specific copy beyond what's already in the data files.
 *
 * **Question philosophy** — every template is about one of three
 * things: a real *place* the couple is visiting, a real *attraction*
 * (its description, its region, its tag), or a real *word / phrase*
 * the day teaches. Meta-trip filler ("how many stops does this day
 * have?", "what day of the week is day 2?") is intentionally absent —
 * this is fun couple trivia, not a data-structure quiz.
 *
 * Each template:
 *   - takes the day + the rest of the itinerary as input,
 *   - returns a single `QuizQuestion` *only if* it has enough data
 *     to ask a meaningful question (otherwise returns null and the
 *     selector skips it),
 *   - sources its distractors from OTHER attractions / words / towns
 *     in the trip so wrong answers stay plausibly trip-flavored.
 *
 * The selector then runs all templates, drops the nulls, deduplicates
 * by question text, and trims to the requested count. If we still
 * can't fill the count we just return what we got — the orchestrator
 * treats any non-empty fallback as playable.
 */

import { itinerary } from "../../data/itinerary";
import { attractions, getAttraction } from "../../data/attractions";
import { localizeDay, localizePoi } from "../../data/i18n";
import type {
  AttractionQuizFact,
  Day,
  PhraseOfDay,
  POI,
  Quiz,
  QuizQuestion
} from "../../data/types";
import type { Lang } from "../lang";
import { QUESTIONS_PER_OFFLINE_PACK } from "./generateQuiz";

const OPTIONS_PER_QUESTION = 4;

/** Micro-dictionary of host reaction lines, and friendly category
 *  labels for attraction tags used in generic questions. */
const COPY = {
  correct: ["Nailed it!", "Spot on!", "Correct!", "You got it!", "Yes!"],
  wrong: ["Close one!", "Almost!", "Not quite —", "Ah, nope —", "The answer is"],
  tag: {
    water: "water adventures",
    extreme: "thrills and adrenaline",
    nature: "nature and trails",
    culture: "history and culture",
    family: "easy fun for two",
    food: "local food and drink",
    view: "unforgettable views",
    cave: "exploring caves and canyons",
    village: "wandering a small town",
    trail: "a good trail",
    "national-park": "a national park"
  } as Record<string, string>
} as const;

function pickReactions(rng: () => number): { reactionCorrect: string; reactionWrong: string } {
  const correct = COPY.correct[Math.floor(rng() * COPY.correct.length)];
  const wrong = COPY.wrong[Math.floor(rng() * COPY.wrong.length)];
  return { reactionCorrect: correct, reactionWrong: wrong };
}

/** Tiny seeded RNG so the same `(day, lang)` combo always produces
 *  the same fallback quiz — replaying gets the same set, no
 *  flicker, no surprises. mulberry32 is good enough for shuffles
 *  and 4-option picks; we don't need cryptographic strength here. */
function mulberry32(seed: number): () => number {
  let s = seed >>> 0;
  return function () {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffleInPlace<T>(arr: T[], rng: () => number): T[] {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/** Pick `n` distractors from `pool`, skipping anything that matches
 *  `correct` (case-insensitive) and any duplicates. Returns fewer
 *  than `n` if the pool is too small — the template caller treats
 *  that as a "skip me" signal. */
function pickDistractors(
  pool: string[],
  correct: string,
  n: number,
  rng: () => number
): string[] {
  const seen = new Set<string>([correct.trim().toLowerCase()]);
  const candidates: string[] = [];
  for (const raw of pool) {
    const v = raw?.trim();
    if (!v) continue;
    const k = v.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    candidates.push(v);
  }
  shuffleInPlace(candidates, rng);
  return candidates.slice(0, n);
}

/** Wrap a question + correct answer + distractors into a real
 *  `QuizQuestion`, randomizing the slot the correct option sits in.
 *  Returns null if we don't have enough distractors to make 4 options. */
function buildQ(opts: {
  question: string;
  correct: string;
  distractors: string[];
  rng: () => number;
}): QuizQuestion | null {
  if (opts.distractors.length < OPTIONS_PER_QUESTION - 1) return null;

  const distractors = opts.distractors.slice(0, OPTIONS_PER_QUESTION - 1);
  const correctSlot = Math.floor(opts.rng() * OPTIONS_PER_QUESTION);
  const options: string[] = [];
  let dIdx = 0;
  for (let i = 0; i < OPTIONS_PER_QUESTION; i++) {
    if (i === correctSlot) {
      options.push(opts.correct);
    } else {
      options.push(distractors[dIdx++]);
    }
  }

  const reactions = pickReactions(opts.rng);
  return {
    question: opts.question,
    options,
    correctIndex: correctSlot,
    reactionCorrect: reactions.reactionCorrect,
    reactionWrong: `${reactions.reactionWrong} ${opts.correct}`
  };
}

/* ------------------------------------------------------------------ */
/* USA + Hawaii wildcard bank                                          */
/* ------------------------------------------------------------------ */

/** A small bank of fun-couple-trivia-tone general facts about the
 *  trip's destinations — national parks, Vegas, and Hawaii. Used by
 *  `tplTripCulture` as a controlled wildcard sprinkled into the
 *  offline pack so the deck doesn't feel repetitive on attraction-thin
 *  days. The pack is still primarily about today's attractions; the
 *  selector caps how many of these can fire (see `MAX_CULTURE`). */
const TRIP_CULTURE_FACTS: AttractionQuizFact[] = [
  {
    question: "How many US national parks does this trip visit?",
    correctAnswer: "Four — Yosemite, Sequoia, Death Valley, and Hawaiʻi Volcanoes",
    distractors: ["Just one", "Ten", "None — they're all state parks"]
  },
  {
    question: "What is the US emergency number?",
    correctAnswer: "911",
    distractors: ["112", "999", "000"]
  },
  {
    question: "What is the legal drinking age in Nevada?",
    correctAnswer: "21",
    distractors: ["18", "16", "There isn't one"]
  },
  {
    question: "What's the standard restaurant tip in the US?",
    correctAnswer: "15–20% of the bill",
    distractors: ["Tipping isn't expected", "1–2%", "50%"]
  },
  {
    question: "Which side of the road do you drive on in the US?",
    correctAnswer: "The right",
    distractors: ["The left", "Either side", "The middle"]
  },
  {
    question: "What does the America the Beautiful annual pass cover?",
    correctAnswer: "Entrance to National Park Service sites for the whole vehicle",
    distractors: ["Free gas nationwide", "Hotel discounts", "Airline upgrades"]
  },
  {
    question: "Is Grand Canyon West covered by the America the Beautiful pass?",
    correctAnswer: "No — it's Hualapai tribal land with its own fees",
    distractors: ["Yes, fully covered", "Only for the Skywalk", "Only on weekdays"]
  },
  {
    question: "What sunscreen ingredient is banned by Hawaii state law to protect reefs?",
    correctAnswer: "Oxybenzone (and octinoxate)",
    distractors: ["Zinc oxide", "Titanium dioxide", "Aloe vera"]
  },
  {
    question: "What does 'aloha' mean, beyond hello and goodbye?",
    correctAnswer: "Love or affection",
    distractors: ["Danger", "Slow down", "Welcome tourist"]
  },
  {
    question: "What is a lūʻau?",
    correctAnswer: "A traditional Hawaiian feast with music and hula",
    distractors: ["A type of canoe", "A volcano crater", "A surfboard"]
  },
  {
    question: "What is 'aa' in Hawaiian volcanology?",
    correctAnswer: "Rough, jagged cooled lava",
    distractors: ["Smooth, ropy lava", "A type of volcano", "A lava tube"]
  },
  {
    question: "What is the tallest mountain in Hawaii, measured base to peak?",
    correctAnswer: "Mauna Kea",
    distractors: ["Haleakalā", "Mauna Loa", "Diamond Head"]
  },
  {
    question: "Which US state is entirely made up of islands?",
    correctAnswer: "Hawaii",
    distractors: ["Florida", "Alaska", "Rhode Island"]
  },
  {
    question: "What's the elevation of Badwater Basin in Death Valley?",
    correctAnswer: "282 feet below sea level",
    distractors: ["At sea level", "282 feet above sea level", "1,000 feet below sea level"]
  },
  {
    question: "What is the largest tree on Earth by volume?",
    correctAnswer: "The General Sherman Tree, a giant sequoia",
    distractors: ["A California redwood", "A baobab tree", "A banyan tree"]
  },
  {
    question: "What US city is famous for its casinos and 24-hour lifestyle on 'the Strip'?",
    correctAnswer: "Las Vegas",
    distractors: ["Reno", "Atlantic City", "Los Angeles"]
  },
  {
    question: "What Arizona slot canyon is famous for its light beams and swirling walls?",
    correctAnswer: "Antelope Canyon",
    distractors: ["Bryce Canyon", "Zion Canyon", "Grand Canyon"]
  },
  {
    question: "What color is genuine Hawaiian 'green sand', found at Papakōlea Beach?",
    correctAnswer: "Olive green, from olivine crystals",
    distractors: ["Bright emerald from dye", "Blue-green from algae", "Neon from minerals unique to Maui"]
  }
];

/* ------------------------------------------------------------------ */
/* Templates — ALL substantive (places / attractions / phrases)        */
/* ------------------------------------------------------------------ */

interface TemplateContext {
  rng: () => number;
  day: Day;
  /** Other days, already localized. */
  otherDays: Day[];
  /** All attractions visited up to this day, already localized —
   *  used as a wide distractor pool. */
  allAttractions: POI[];
  /** Just the attractions the couple visits *today*, localized.
   *  Templates use this for the "correct" answer when the question
   *  is grounded in the day's plan. */
  todaysAttractions: POI[];
}

/** Q: what does the word/phrase X mean? */
function tplPhraseMeaning(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, rng } = ctx;
  const words: PhraseOfDay[] = day.phrasesOfDay ?? [];
  if (words.length === 0) return null;
  const w = words[Math.floor(rng() * words.length)];
  if (!w?.meaning) return null;
  const otherMeanings = otherDays
    .flatMap(d => (d.phrasesOfDay ?? []).map(o => o.meaning))
    .filter(Boolean);
  const distractors = pickDistractors(otherMeanings, w.meaning, OPTIONS_PER_QUESTION - 1, rng);
  return buildQ({
    question: `What does "${w.word}" mean?`,
    correct: w.meaning,
    distractors,
    rng
  });
}

/** Q: which word/phrase means [meaning]? — reverse of tplPhraseMeaning. */
function tplPhraseReverse(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, rng } = ctx;
  const words: PhraseOfDay[] = day.phrasesOfDay ?? [];
  if (words.length === 0) return null;
  const w = words[Math.floor(rng() * words.length)];
  if (!w?.word || !w?.meaning) return null;
  const otherWords = otherDays
    .flatMap(d => (d.phrasesOfDay ?? []).map(o => o.word))
    .filter(Boolean);
  const distractors = pickDistractors(otherWords, w.word, OPTIONS_PER_QUESTION - 1, rng);
  return buildQ({
    question: `Which word/phrase means "${w.meaning}"?`,
    correct: w.word,
    distractors,
    rng
  });
}

/** Q: a fun-couple-trivia fact pulled from `TRIP_CULTURE_FACTS`. The
 *  selector caps how many of these are allowed per pack — the deck
 *  stays primarily about the day's actual attractions, with one or
 *  two of these sprinkled in for variety on attraction-thin days. */
function tplTripCulture(ctx: TemplateContext): QuizQuestion | null {
  const { rng } = ctx;
  const bank = TRIP_CULTURE_FACTS;
  if (!bank || bank.length === 0) return null;
  const fact = bank[Math.floor(rng() * bank.length)];
  return buildQ({
    question: fact.question,
    correct: fact.correctAnswer,
    distractors: fact.distractors,
    rng
  });
}

/** Q: a hand-curated story / science / signature-detail question
 *  about an attraction the couple visits today. Pulls from the
 *  attraction's `quizFacts` array (authored alongside its
 *  description in `attractions.ts`) — deliberately FIRST in the
 *  template list so it dominates the offline pack on any day with
 *  story-rich attractions. */
function tplAttractionStory(ctx: TemplateContext): QuizQuestion | null {
  const { todaysAttractions, rng } = ctx;
  type Pair = { att: POI; fact: AttractionQuizFact };
  const catalog: Pair[] = [];
  for (const att of todaysAttractions) {
    if (!att.quizFacts) continue;
    for (const fact of att.quizFacts) {
      if (!fact.question || !fact.correctAnswer) continue;
      if (!fact.distractors || fact.distractors.length < OPTIONS_PER_QUESTION - 1) continue;
      catalog.push({ att, fact });
    }
  }
  if (catalog.length === 0) return null;

  const pick = catalog[Math.floor(rng() * catalog.length)];
  return buildQ({
    question: pick.fact.question,
    correct: pick.fact.correctAnswer,
    distractors: pick.fact.distractors,
    rng
  });
}

const WORD_TEMPLATES: Array<(ctx: TemplateContext) => QuizQuestion | null> = [
  tplPhraseMeaning,
  tplPhraseReverse
];

const TEMPLATES: Array<(ctx: TemplateContext) => QuizQuestion | null> = [
  // Curated story trivia first — when the attraction author has
  // written quizFacts for today's stops, these are the highest-
  // quality questions in the deck.
  tplAttractionStory
];

/* ------------------------------------------------------------------ */
/* Public entry point                                                  */
/* ------------------------------------------------------------------ */

/**
 * Build a fallback `Quiz` of up to `count` questions for `(day, lang)`,
 * deterministic per `(day, count)`. Throws only if there is no
 * itinerary entry for the day at all (the orchestrator surfaces that
 * as a real error). If templates can't fill the requested count, the
 * returned quiz is shorter — the orchestrator treats any non-empty
 * fallback as playable.
 */
export function buildFallbackQuiz(
  dayNumber: number,
  _lang: Lang,
  count: number = QUESTIONS_PER_OFFLINE_PACK
): Quiz {
  const rawDay = itinerary.find(d => d.dayNumber === dayNumber);
  if (!rawDay) {
    throw new Error(`No itinerary entry for day ${dayNumber}`);
  }

  const day = localizeDay(rawDay);
  const otherDays = itinerary.filter(d => d.dayNumber !== dayNumber).map(d => localizeDay(d));

  const pastDays = itinerary.filter(d => d.dayNumber <= dayNumber);
  const pastAttractionIds = new Set(
    pastDays.flatMap(d => d.activities.map(a => a.attractionId).filter(Boolean))
  );

  const allAttractions = attractions
    .filter(a => pastAttractionIds.has(a.id))
    .map(a => localizePoi(a));

  const todaysAttractions: POI[] = day.activities
    .map(a => (a.attractionId ? getAttraction(a.attractionId) : null))
    .filter((a): a is POI => Boolean(a))
    .map(a => localizePoi(a));

  const seed = dayNumber * 1009 + 13 + count * 31;
  const rng = mulberry32(seed);

  const ctx: TemplateContext = {
    rng,
    day,
    otherDays,
    allAttractions,
    todaysAttractions
  };

  const collected: QuizQuestion[] = [];
  const seen = new Set<string>();
  const tryAdd = (q: QuizQuestion | null) => {
    if (!q) return;
    if (collected.length >= count) return;
    const key = q.question.trim().toLowerCase();
    if (seen.has(key)) return;
    seen.add(key);
    collected.push(q);
  };

  // PASS 1 — Words/phrases (Target 1-2 questions).
  const MAX_WORDS = todaysAttractions.length < 2 ? 1 : 2;
  let wordsAdded = 0;
  for (let pass = 0; pass < 3 && wordsAdded < MAX_WORDS && collected.length < count; pass++) {
    const order = shuffleInPlace([...WORD_TEMPLATES.keys()], rng);
    for (const idx of order) {
      if (wordsAdded >= MAX_WORDS || collected.length >= count) break;
      const before = collected.length;
      tryAdd(WORD_TEMPLATES[idx](ctx));
      if (collected.length > before) wordsAdded++;
    }
  }

  // PASS 2 — Trip-culture wildcards (Target ~4 questions, or more if
  // few attractions today).
  const MAX_CULTURE = todaysAttractions.length < 2 ? count - wordsAdded : 4;
  let cultureAdded = 0;
  for (
    let i = 0;
    i < MAX_CULTURE * 4 && cultureAdded < MAX_CULTURE && collected.length < count;
    i++
  ) {
    const before = collected.length;
    tryAdd(tplTripCulture(ctx));
    if (collected.length > before) cultureAdded++;
  }

  // PASS 3 — Curated attraction stories.
  for (let i = 0; i < 10 && collected.length < count; i++) {
    tryAdd(tplAttractionStory(ctx));
  }

  // PASS 4 — fill remaining slots with the generic attraction templates.
  const MAX_PASSES = 4;
  for (let pass = 0; pass < MAX_PASSES && collected.length < count; pass++) {
    const order = shuffleInPlace([...TEMPLATES.keys()], rng);
    for (const idx of order) {
      if (collected.length >= count) break;
      tryAdd(TEMPLATES[idx](ctx));
    }
  }

  shuffleInPlace(collected, rng);

  return {
    day: dayNumber,
    lang: "en",
    questions: collected,
    // Marker timestamp 0 = "this is a fallback, not a real Gemini
    // generation".
    generatedAt: 0
  };
}
